[package]
name = "pokemon-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws_lambda_events = "0.8.3"
http = "0.2.9"
lambda_runtime = "0.7.3"
tokio = "1.27.0"
